# configuration
CONF="/etc/nginx/nginx.conf"
SITES_AVAILABLE="/etc/nginx/sites-available"
SITES_ENABLE="/etc/nginx/conf.d" 

DOMAIN="damphat.com"
DOMAIN_FILE="damphat.com.conf"
PORT="3000"

# add a site
mkdir $SITES_AVAILABLE

cd $SITES_AVAILABLE

echo "#generated by /add-node-proxy.sh" > $DOMAIN_FILE
echo "server {" >> $DOMAIN_FILE
echo "    listen 0.0.0.0:80;" >> $DOMAIN_FILE
echo "    server_name $DOMAIN;" >> $DOMAIN_FILE
echo "    access_log /var/log/nginx/$DOMAIN.log;" >> $DOMAIN_FILE
echo "" >> $DOMAIN_FILE
echo "    location / {" >> $DOMAIN_FILE
echo "      proxy_set_header X-Real-IP \$remote_addr;" >> $DOMAIN_FILE
echo "      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >> $DOMAIN_FILE
echo "      proxy_set_header Host \$http_host;" >> $DOMAIN_FILE
echo "      proxy_set_header X-NginX-Proxy true;" >> $DOMAIN_FILE
echo "" >> $DOMAIN_FILE
echo "      proxy_pass http://127.0.0.1:$PORT;" >> $DOMAIN_FILE
echo "      proxy_redirect off;" >> $DOMAIN_FILE

#support websocket
echo "      proxy_http_version 1.1;" >> $DOMAIN_FILE
echo "      proxy_set_header Upgrade \$http_upgrade;" >> $DOMAIN_FILE
echo "      proxy_set_header Connection "upgrade";" >> $DOMAIN_FILE

echo "    }" >> $DOMAIN_FILE
echo " }" >> $DOMAIN_FILE

rm -f "$SITES_ENABLE/$DOMAIN_FILE"
ln -s "$SITES_AVAILABLE/$DOMAIN_FILE" "$SITES_ENABLE/$DOMAIN_FILE"

service nginx restart
echo "DONE!"
