if [ $# != 2 ]; then
	echo 'Usage: nginx/vhost/add-proxy.sh <domain> <proxyport>'
	echo 
	echo Example 1: nginx/vhost/add-proxy.sh damphat.com 3000
	echo Example 2: nginx/vhost/add-proxy.sh *.damphat.com 3000
	exit 1
fi

set -x
trap read debug

# configuration
#TODO: detect configuration directoy

SITES_AVAILABLE="/etc/nginx/sites-available"
SITES_ENABLE="/etc/nginx/conf.d" 

which nginx || { echo nginx does not exist; exit 1; }
test -d $SITES_ENABLE || { echo $SITES_ENABLE does not exist; exit 1; }

DOMAIN="$1"
DOMAIN_CONF=${DOMAIN//\*/_}.conf
DOMAIN_LOG=${DOMAIN//\*/_}.log
PORT="$2"

# add a site
test -d $SITES_AVAILABLE || mkdir $SITES_AVAILABLE

cd $SITES_AVAILABLE
cat > $DOMAIN_CONF <<_EOF_
#generated by nginx/vhost/add-proxy.sh
server {
    listen 0.0.0.0:80;
    server_name $DOMAIN;
    access_log /var/log/nginx/$DOMAIN_LOG;

    location / {
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_set_header Host \$http_host;
      proxy_set_header X-NginX-Proxy true;

      proxy_pass http://127.0.0.1:$PORT;
      proxy_redirect off;

      #support websocket
      proxy_http_version 1.1;
      proxy_set_header Upgrade \$http_upgrade;
      proxy_set_header Connection "upgrade";
    }
}
_EOF_

rm -f "$SITES_ENABLE/$DOMAIN_CONF"
ln -s "$SITES_AVAILABLE/$DOMAIN_CONF" "$SITES_ENABLE/$DOMAIN_CONF"

nginx -s reload
echo "DONE!"
